[package]
name = "yuno-faqman"
version = "0.2.0"
edition = "2024"

[dependencies]
crossterm = "0.29"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"

[[bin]]
name = "yuno-faqman"
path = "main.rs"
